"""empty message

Revision ID: 3e817d7c27e5
Revises: b4f085517970
Create Date: 2020-03-23 11:13:37.377850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e817d7c27e5'
down_revision = 'b4f085517970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'donations', type_='foreignkey')
    op.drop_constraint(None, 'donations', type_='foreignkey')
    op.create_foreign_key(None, 'donations', 'user', ['username'], ['username'])
    op.create_foreign_key(None, 'donations', 'NGO', ['orgname'], ['orgname'])
    op.drop_column('donations', 'org_id')
    op.drop_column('donations', 'user_id')
    op.create_foreign_key(None, 'volunteer', 'NGO', ['related_with'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volunteer', type_='foreignkey')
    op.add_column('donations', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('donations', sa.Column('org_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'donations', type_='foreignkey')
    op.drop_constraint(None, 'donations', type_='foreignkey')
    op.create_foreign_key(None, 'donations', 'NGO', ['org_id'], ['id'])
    op.create_foreign_key(None, 'donations', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
