"""empty message

Revision ID: db9d184e7acc
Revises: ad0df56a6e84
Create Date: 2020-03-23 10:39:20.036542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9d184e7acc'
down_revision = 'ad0df56a6e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NGO',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orgname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('field_of_work', sa.String(length=100), nullable=True),
    sa.Column('about', sa.String(length=207), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_NGO_email'), 'NGO', ['email'], unique=True)
    op.create_index(op.f('ix_NGO_orgname'), 'NGO', ['orgname'], unique=True)
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['NGO.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'volunteer', 'NGO', ['related_with'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volunteer', type_='foreignkey')
    op.drop_table('donations')
    op.drop_index(op.f('ix_NGO_orgname'), table_name='NGO')
    op.drop_index(op.f('ix_NGO_email'), table_name='NGO')
    op.drop_table('NGO')
    # ### end Alembic commands ###
